import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { useApp } from "@/context/AppContext";
import ModalOverlay from "@/components/ModalOverlay";
import { Sparkles, Send, Camera, Mic, Wrench, Zap, Droplets, Paintbrush } from "lucide-react";

interface Message {
  id: string;
  text: string;
  sender: "ai" | "user";
  isPreview?: boolean;
}

const quickChips = [
  { icon: <Droplets className="w-3.5 h-3.5" />, label: "Problema Hidráulico" },
  { icon: <Zap className="w-3.5 h-3.5" />, label: "Problema Elétrico" },
  { icon: <Paintbrush className="w-3.5 h-3.5" />, label: "Diarista" },
  { icon: <Wrench className="w-3.5 h-3.5" />, label: "Serviços Gerais" },
];

export default function AIPostBuilderModal() {
  const { openModal, setOpenModal } = useApp();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "ai-1",
      text: "Olá! Sou o assistente inteligente do SeverinoApp. Me conte o que você precisa ou envie uma foto do problema que eu monto o anúncio para você!",
      sender: "ai",
    },
  ]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const chatRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatRef.current?.scrollTo({ top: chatRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, isTyping]);

  const sendMessage = (text: string) => {
    if (!text.trim()) return;
    const userMsg: Message = { id: `u-${Date.now()}`, text, sender: "user" };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);

    setTimeout(() => {
      const aiResponse: Message = {
        id: `ai-${Date.now()}`,
        text: "Entendi! Analisei o problema e preparei seu anúncio. Veja a prévia abaixo:",
        sender: "ai",
      };
      setMessages((prev) => [...prev, aiResponse]);

      setTimeout(() => {
        const previewMsg: Message = {
          id: `preview-${Date.now()}`,
          text: "",
          sender: "ai",
          isPreview: true,
        };
        setMessages((prev) => [...prev, previewMsg]);
        setIsTyping(false);
      }, 500);
    }, 1500);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    sendMessage(input);
  };

  return (
    <ModalOverlay isOpen={openModal === "aiBuilder"} onClose={() => { setOpenModal(null); setMessages([{ id: "ai-1", text: "Olá! Sou o assistente inteligente do SeverinoApp. Me conte o que você precisa ou envie uma foto do problema que eu monto o anúncio para você!", sender: "ai" }]); }} maxWidth="max-w-2xl" fullHeight>
      {/* Header */}
      <div className="flex items-center gap-3 p-4 border-b border-border shrink-0">
        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-accent flex items-center justify-center">
          <Sparkles className="w-4 h-4 text-accent-foreground" />
        </div>
        <h2 className="font-display text-lg font-bold text-foreground">Assistente Severino</h2>
      </div>

      {/* Chat area */}
      <div ref={chatRef} className="flex-1 overflow-y-auto p-4 space-y-4 bg-secondary/50">
        {messages.map((msg) => {
          if (msg.isPreview) {
            return (
              <div key={msg.id} className="max-w-sm">
                <div className="bg-card border-2 border-indigo-200 rounded-2xl shadow-card p-4">
                  <p className="text-xs text-muted-foreground mb-2">📋 Prévia do seu anúncio</p>
                  <div className="w-full h-32 bg-secondary rounded-xl mb-3 flex items-center justify-center text-muted-foreground text-xs">Foto do problema</div>
                  <span className="inline-block bg-destructive text-destructive-foreground text-xs font-bold px-2 py-0.5 rounded-full mb-2">URGENTE</span>
                  <h4 className="font-display font-bold text-foreground mb-1">Vazamento forte na pia da cozinha</h4>
                  <p className="text-sm text-muted-foreground mb-3">Preciso de um encanador urgente para resolver um vazamento no sifão da pia da cozinha...</p>
                  <div className="flex items-center gap-3 text-xs text-muted-foreground mb-4">
                    <span>📂 Hidráulica</span>
                    <span>💰 R$ 80 - R$ 200</span>
                    <span>📍 Seu bairro</span>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" className="flex-1">Refazer texto</Button>
                    <Button size="sm" className="flex-1">🚀 Publicar Agora</Button>
                  </div>
                  <p className="text-[10px] text-muted-foreground mt-2 text-center">Generated by Severino AI</p>
                </div>
              </div>
            );
          }

          return (
            <div key={msg.id} className={`flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}>
              {msg.sender === "ai" && (
                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-accent flex items-center justify-center mr-2 shrink-0 mt-1">
                  <Sparkles className="w-3.5 h-3.5 text-accent-foreground" />
                </div>
              )}
              <div
                className={`max-w-sm px-4 py-3 text-sm ${
                  msg.sender === "user"
                    ? "bg-foreground text-card rounded-2xl rounded-tr-sm"
                    : "bg-card border border-border rounded-2xl rounded-tl-sm shadow-sm"
                }`}
              >
                {msg.text}
              </div>
            </div>
          );
        })}

        {isTyping && (
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-accent flex items-center justify-center shrink-0">
              <Sparkles className="w-3.5 h-3.5 text-accent-foreground" />
            </div>
            <div className="bg-card border border-border rounded-2xl rounded-tl-sm px-4 py-3 flex gap-1">
              <span className="w-2 h-2 bg-muted-foreground rounded-full animate-ai-pulse" style={{ animationDelay: "0ms" }} />
              <span className="w-2 h-2 bg-muted-foreground rounded-full animate-ai-pulse" style={{ animationDelay: "200ms" }} />
              <span className="w-2 h-2 bg-muted-foreground rounded-full animate-ai-pulse" style={{ animationDelay: "400ms" }} />
            </div>
          </div>
        )}

        {messages.length === 1 && !isTyping && (
          <div className="flex flex-wrap gap-2 mt-2">
            {quickChips.map((chip) => (
              <button
                key={chip.label}
                onClick={() => sendMessage(chip.label)}
                className="flex items-center gap-1.5 bg-card border border-border text-foreground rounded-full px-4 py-2 text-sm hover:border-accent hover:text-accent hover:bg-indigo-50 transition-colors"
              >
                {chip.icon} {chip.label}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Input */}
      <form onSubmit={handleSubmit} className="p-4 border-t border-border shrink-0 flex items-center gap-2">
        <button type="button" className="p-2 text-muted-foreground hover:text-foreground">
          <Camera className="w-5 h-5" />
        </button>
        <button type="button" className="p-2 text-muted-foreground hover:text-foreground">
          <Mic className="w-5 h-5" />
        </button>
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          className="flex-1 border border-border rounded-2xl px-4 py-3 bg-card text-foreground text-sm"
          placeholder="Digite sua mensagem..."
        />
        <Button type="submit" variant="ai" size="icon" disabled={!input.trim()}>
          <Send className="w-4 h-4" />
        </Button>
      </form>
    </ModalOverlay>
  );
}
